# 2.3 Método da Eliminação de Gauss

Os métodos diretos de eliminação consistem no processo 
de transformar um sistema de equações lineares $Ax=b$, em que $A= (a_{ij})_i,j=1,..,n$, 
$x=(x_1,x_2,...,x_n)^t$ e $b=(b_1, b_2,...,b_n)^t$, em um sistema equivalente, 
aplicando operações elementares sobre as linhas da matriz $(A,b)$.

O sistema equivalente obtido ao final do processo, deve ser de 
resolução mais simples ou imediata, por substituição direta. No caso da eliminação de Gauss 
com pivoteamento diagonal ou pivoteamento parcial, obtém-se um sistema equivalente 
na forma triangular. No caso da eliminação de Gauss-Jordan o sistema equivalente 
obtido possui a matriz de coeficientes igual a matriz identidade.   


Em geral, consideraremos neste texto, um sistema linear escrito na forma geral como  

$$ \begin{cases} 
	         a_{11}x_1 +a_{12}x_2 + \cdots + a_{1n}x_n = b_1\\ 
	         a_{21}x_1 +a_{22}x_2 + \cdots + a_{2n}x_n = b_2\\
	         \vdots   \\
	         a_{n1}x_1 +a_{n2}x_2 + \cdots + a_{nn}x_n = b_1\\
	         \end{cases} $$
             
cuja forma forma matricial $Ax=b$ tem a seguinte representação
            
$$\left[\begin{array}{cccc} 
	         a_{11} & a_{12} & \cdots & a_{1n} \\ 
	         a_{21} & a_{22} & \cdots & a_{2n} \\
	         \vdots & \vdots & \vdots & \vdots \\
	         a_{n1} & a_{n2} & \cdots & a_{nn} \\
	         \end{array} \right]
\left[\begin{array}{c} 
	         x_1 \\ 
	         x_2 \\
             \vdots\\
	         x_n \\
	         \end{array} \right]
=
\left[\begin{array}{c} 
	         b_1 \\ 
	         b_2 \\
             \vdots\\
	         b_n \\
	         \end{array} \right]
	         $$
	         
e a matriz aumentada $(A,b)$ é dada por  

$$\left[\begin{array}{cccccc} 
	         a_{11} & a_{12} & \cdots & a_{1n} & | & b_1\\ 
	         a_{21} & a_{22} & \cdots & a_{2n} & | & b_2\\
	         \vdots & \vdots & \vdots & \vdots & | & \vdots\\
	         a_{n1} & a_{n2} & \cdots & a_{nn} & | & b_n\\
	         \end{array} \right]$$
	         



O processo de **eliminação de Gauss** com pivoteamento diagonal consiste em transformar 
o sistema em um sistema equivalente triangular superior por meio de operações 
elementares sobre as linhas da matriz $(A,b)$ tomando, em cada passo, como pivô,
os elementos da diadonal de $A$, desde que não seja nulo. Caso o algum elemento da 
diagonal seja nulo podemos permutar duas linhas da matriz a fim obter um pivô 
diferente de zero.

Para cada passo $k$ do processo, anulamos os termos abaixo do 
elemento da diagonal $a_{kk}$, subtraindo cada linha $i=k+1$ da matriz $(A,b)$, 
pela linha linha anterior, $i=k$, multiplicada pelo fator $m_{ik}=\frac{a_{ik}}{a_{kk}}$.

Assim, no 1º passo ($k=1$), fazemos $m_{i1}=\frac{a_{i1}}{a_{k1}}$, $i=2,...,n$ 
e cada linha de $(A,b)$, a partir da 2ª, será subtraída da 1ª linha multiplicada por
$m_{k1}$ obtendo-se a matriz $(A^{(1)},b^{(1)})$ tal que


$$(A^{(1)},b^{(1)}) = \left[\begin{array}{ccccccc} 
	         a^{(1)}_{11} & a^{(1)}_{12} & a^{(1)}_{13} & \cdots & a^{(1)}_{1n} & | & b^{(1)}_1\\ 
	         0            & a^{(2)}_{22} & a^{(2)}_{23} & \cdots & a^{(2)}_{2n} & | & b^{(2)}_2\\
	         0            & a^{(2)}_{32} & a^{(2)}_{33} & \cdots & a^{(2)}_{3n} & | & b^{(2)}_3\\
	         \vdots       & \vdots       & \vdots       & \vdots & \vdots       & | & \vdots   \\
	         0            & a^{(2)}_{n2} & a^{(2)}_{n3} & \cdots & a^{(2)}_{nn} & | & b^{(2)}_n\\
	         \end{array} \right]$$
             

No 2º passo ($k=2$), fazemos $m_{i2}=\frac{a_{i2}}{a_{k2}}$, $i=3,...,n$ 
e cada linha de $(A^{(1)},b^{(1)})$, a partir da 3ª, será subtraída da 2ª linha multiplicada por
$m_{k2}$ obtendo-se a matriz $(A^{(2)},b^{(2)})$ tal que

$$(A^{(2)},b^{(2)}) = \left[\begin{array}{ccccccc} 
	         a^{(1)}_{11} & a^{(1)}_{12} & a^{(1)}_{13} & \cdots & a^{(1)}_{1n} & | & b^{(1)}_1\\ 
	         0            & 0            & a^{(2)}_{23} & \cdots & a^{(2)}_{2n} & | & b^{(2)}_2\\
	         0            & 0            & a^{(3)}_{33} & \cdots & a^{(3)}_{3n} & | & b^{(3)}_3\\
	         \vdots       & \vdots       & \vdots       & \vdots & \vdots       & | & \vdots   \\
	         0            & 0            & a^{(3)}_{n3} & \cdots & a^{(3)}_{nn} & | & b^{(3)}_n\\
	         \end{array} \right]$$

Segundo os passos seguintes, até o passo $n-1$, obtemos ou sistema triangular superior na forma   
 
$$ \begin{cases} 
	         a^{(1)}_{11}x_1 + a^{(1)}_{12}x_2 + a^{(1)}_{13}x_2 + \cdots + a^{(1)}_{1n}x_n = b^{(1)}_1\\ 
             \hspace{65px}     a^{(2)}_{22}x_2 + a^{(2)}_{23}x_2 + \cdots + a^{(2)}_{2n}x_n = b^{(2)}_2\\ 
             \hspace{65px}     \hspace{65px}     a^{(3)}_{33}x_2 + \cdots + a^{(3)}_{3n}x_n = b^{(3)}_3\\ 
 	         \hspace{65px}     \hspace{65px}      \hspace{65px}     \hspace{45px}      \vdots   \\
	         \hspace{65px}     \hspace{65px}      \hspace{65px}     \hspace{45px}  a^{(n)}_{nn}x_n = b^{(n)}_n\\ 
	         \end{cases} $$

O qual pode ser resolvido por substituição retroativa.



In [1]:
import numpy as np

M = np.array([[3.,2.,4.,1.],
              [1.,1.,2.,2.],
              [-4.,3.,2.,3.]])

# Pega o numero de linhas de M
n = len(M)
print (n)

for j in range(n-1):
    for i in range(j,n-1):
        m = M[i+1,j]/M[j,j]
        M[i+1] = M[i+1]-m*M[j]

        
b = M[0:n+1,n:n+1]       
A = M[0:n+1,0:n]  

print (np.round(b,4))
print (np.round(A,4))

#funcao para resolver um sistema triangular superior
def solve(U, y):
    n = len(U)-1       #os indices correm de 0 ate n-1
    xn = y[n]/U[n][n]

    x = [0]*len(U)     # cria um vetor de zeros    
    x[-1] = xn         # atribui xn na ultima posicao de x
    
    for i in range(n-1,-1,-1):
        soma = 0
        for j in range(i+1,n+1):
            soma +=  U[i][j]*x[j]
        xi = (y[i]-soma)/U[i][i]
        x[i] = xi
    return x

print (solve(A,b))


3
[[  1.    ]
 [  1.6667]
 [-24.    ]]
[[ 3.      2.      4.    ]
 [ 0.      0.3333  0.6667]
 [ 0.      0.     -4.    ]]
[array([-3.]), array([-7.]), array([ 6.])]


Outro algoritmo

In [2]:
import numpy as np
from numpy import dot
def gaussElimin(a,b): 
    n = len(b) 
    for k in range(0,n-1): 
        for i in range(k+1,n): 
            if a[i][k] != 0.0: 
                lam = a [i][k]/a[k][k] 
                a[i][k+1:n] = a[i][k+1:n] - lam*a[k][k+1:n] 
                b[i] = b[i] - lam*b[k] 
    for k in range(n-1,-1,-1): 
        b[k] = (b[k] - dot(a[k][k+1:n],b[k+1:n]))/a[k][k] 
    return b

A = np.array([[3.,2.,4.,1.],
     [1.,1.,2.,2.],
     [-4.,3.,2.,3.]])
b = np.array([1., 2., 3.])

print (gaussElimin(A,b))

[-3. -7.  6.]


In [3]:
import numpy as np
A = np.array([[ 3.,2.,4.],
              [ 1.,1.,2.],
              [4.,3.,2.]])

b = np.array([1., 2., 3.])

n = len(b)
 

for j in range(0,n):
    for i in range(j+1,n):
        mij = A[i][j]/A[j][j]
        A[i][j:n] = A[i][j:n] - mij*A[j][j:n]
        b[i] = b[i] - mij*b[j] 
print (np.round(A,4), b)
              


[[ 3.      2.      4.    ]
 [ 0.      0.3333  0.6667]
 [ 0.      0.     -4.    ]] [  1.00000000e+00   1.66666667e+00  -4.44089210e-16]
