# 2.4 Método por inversão de matrizes

Considere o sistema de $n$ equações e $n$ variáveis dado por 

$$ Ax=b$$

Se a matriz $A$ dos coeficientes for não singular, ou seja, se o sistema possuir solução única a matriz é invertível e a solução do sistema pode ser obtida multiplicando-se a inversa $A^{-1}$ à esquerda de ambos os lados da equação, como segue: 

$$A^{-1}Ax=A^{-1}b$$
logo
$$Ix = A^{-1}b$$
ou
$$x = A^{-1}b$$
Que é a solução do sistema linear.

### Exemplo
Resolver o sistema $Ax=b$ com $A = 
 \left[\begin{array}{ccc} 
	         3 & 0 & 1 \\ 
	         3 & 2 & 1 \\
            -3 & 1 & 3 \\
	     \end{array} \right]$
e $b = (1,1,3)^t$.    

In [116]:
import numpy as np
from numpy.linalg import inv

A = np.array([[3,0,1],[3,2,1],[-3,1,3]])
b = np.array([1,1,3])
x = np.dot(inv(A),b)
print (np.round(x,4))

[0. 0. 1.]


## Obtenção da matriz inversa



In [104]:
import numpy as np

In [105]:
def gaussJordan(M):
    n = len(M)
    for k in range(n):
        M[k] = M[k]/M[k,k]
        for i in range(n):
            if i!=k:
                M[i] = M[i] - M[i,k]*M[k]
    return (M)

In [106]:
A = np.array([[2,1,3],[0,-1,1],[1,0,3]], float)
I = np.identity(len(A))
M = np.concatenate((A,I), axis=1)
print (M)

[[ 2.  1.  3.  1.  0.  0.]
 [ 0. -1.  1.  0.  1.  0.]
 [ 1.  0.  3.  0.  0.  1.]]


In [107]:
M = gaussJordan(M)
print (M)

[[ 1.   0.   0.   1.5  1.5 -2. ]
 [ 0.   1.   0.  -0.5 -1.5  1. ]
 [ 0.   0.   1.  -0.5 -0.5  1. ]]


In [111]:
Ainv = M[:,3:6]
print(Ainv)

[[ 1.5  1.5 -2. ]
 [-0.5 -1.5  1. ]
 [-0.5 -0.5  1. ]]


### Outra forma de fazer

In [3]:
n = len(A)
for j in range(0,n):
    for i in range(j+1,n):
        mij = A[i][j]/A[j][j]
        A[i][j:n] = A[i][j:n] - mij*A[j][j:n]
        I[i][j:n] = I[i][j:n] - mij*I[j][j:n]

print (np.round(A,4))
print (I)

[[ 1  0  1]
 [ 0  1  2]
 [ 0  0 -1]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -1.  1.]]


In [4]:
b1,b2,b3 =np.split(I, 3, axis=1)
b1 = b1.T[0]
b2 = b2.T[0]
b3 = b3.T[0]
print (b1)
print (b2)
print (b3)

[1. 0. 0.]
[ 0.  1. -1.]
[0. 0. 1.]


In [14]:
def solve_tri(A,b):
    n = len(b)
    for k in range(n-1,-1,-1): 
        b[k] = (b[k] - np.dot(A[k][k+1:n],b[k+1:n]))/A[k][k] 
    return b


c1 = solve_tri(A,b1)
c2 = solve_tri(A,b2)
c3 = solve_tri(A,b3)


print(c1, c2, c3)

M = np.concatenate((c1, c2, c3))

print (M.reshape(3,3))

[1. 0. 0.] [ 0.  1. -1.] [0. 0. 1.]
[[ 1.  0.  0.]
 [ 0.  1. -1.]
 [ 0.  0.  1.]]
