# 2.5 Métodos Iterativos

Em certos casos, os métodos iterativos são mais indicados do que os métodos diretos (exatos), como por exemplo, quando a matriz dos coeficientes é uma matriz esparsa. Eles ainda necessitam de menos memória para armazenamento e  possuem a vantagem de se auto corrigir se um erro é cometido. Além disso, podem ser usados para reduzir os erros de arredondamento na solução obtida por métodos exatos. Podem também, sob certas condições, resolver um conjunto de equações não lineares. Ao usar métodos iterativos, no entanto, precisamos sempre saber se a sequência se soluções aproximadas está
convergindo ou não para a solução desejada.

### Definição
Dados uma sequência de vetores $x^{(k)} \in V$ e uma norma sobre o espaço vetorial $V$, dizemos que a sequência $\{x^{(k)}\}$ converge para $\bar{x} \in V$ se $ \|x^{(k)} - \bar{x}\|  \rightarrow 0$, quando $k \rightarrow \infty$.

Para determinar a solução de um sistema linear por métodos iterativos, precisamos transformar o sistema dado em um outro sistema equivalente que  possa ser definido um processo iterativo.

Suponha então, que o sistema $Ax = b$ seja reescrito na forma equivalente 

$$x = Hx + g$$

tal que a solução $\bar{x}$ de $x = Hx + g$ é  também, solução de $Ax = b$. A partir dessa nova forma podemos obter um processo iterativo que fornecerá a sequência de soluções aproximadas que buscamos.

Assim, seja $x^{(0)}$ uma aproximação inicial para a solução $\bar{x}$, obtemos as aproximações sucessivas $x^{(k)}$ para a solução desejada usando o processo iterativo definido por:

$$x^{(k)} = Hx^{(k-1)} + g$$

### Convergência 
(Franco, 2006, p.169)

### Teorema: 
A condição necessária e suficiente para a convergência do processo iterativo definido por $x = Hx + g$ é que $max \{ |\lambda_i |\} < 1$, onde $\lambda_i$ são os autovalores da matriz $H$. 

### Corolário (Critério geral de convergência):
Como consequência do teorema acima, o processo será convergente se para qualquer norma de matrizes, $\| H \| < 1$.   

#### Prova
Na k-ésima iteração o vetor erro, dado por $e^{(k)}=\bar{x}-x^{(k)}$ será 

$$ e ^{(k)} = H^ke^{(0)}$$

Tomando normas consistentes, tem-se que 

$$ \| H^k e^{(0)} \| \leq \| H \|^k \|e^{(0)}\|$$

portanto 
$$ \| e^{(k)} \| \leq \| H \|^k \|e^{(0)}\|$$

como $\| H \|<1$ tem-se que $\| e^{(k)} \| \rightarrow 0$ quando $k \rightarrow \infty$.

Assim, se $\| H \|<1$ para alguma norma, temos a garantia de que o processo iterativo dado por $ x - x^{(k)} = H(x-x^{(k-1)})$ converge para a solução exata $\bar{x}$. A matriz $H$ é chamada **matriz de iteração**.


## Método iterativo de Jacobi-Richardson

Considere um sistema  de equações lineares $Ax = b$ em que $det(A) \neq 0$, com a diagonal principal $a_{ii} \neq 0$, $i=1,...,n$ como segue

$$ \begin{cases} 
	         a_{11}x_1 +a_{12}x_2 + \cdots + a_{1n}x_n = b_1\\ 
	         a_{21}x_1 +a_{22}x_2 + \cdots + a_{2n}x_n = b_2\\
	         \vdots   \\
	         a_{n1}x_1 +a_{n2}x_2 + \cdots + a_{nn}x_n = b_1\\
             \end{cases} $$

Dividindo cada linha do sistema dado pelo elemento da diagonal e isolando $x_1$ na $1^a$ equação, $x_2$ na $2^a$ equação até $x_n$ na n-ésima equação, temos o sistema escrito na forma equivalente:

$$ \begin{cases} 
	         x_1 = \frac{1}{a_{11}} \left(b_1  - a_{12}x_2 - a_{13}x_3 - \cdots - a_{1n}x_n \right)\\ 
	         x_2 = \frac{1}{a_{22}} \left(b_2  - a_{21}x_1 - a_{23}x_3 - \cdots - a_{2n}x_n \right)\\ 
	         \vdots   \\
	         x_n = \frac{1}{a_{nn}} \left(b_n  - a_{n1}x_1 - a_{n2}x_2 - \cdots - a_{n \, n-1}x_{n-1} \right)\\ 
\end{cases} $$

O método iterativo de Jacobi-Richardson é dado da seguinte forma:

$$ \begin{cases} 
             x_1^{(k+1)} = \frac{b_1}{a_{11}}  - \frac{a_{12}}{a_{11}}x_2^{(k)} - \frac{a_{13}}{a_{11}}x_3^{(k)} - \cdots - \frac{a_{1n}}{a_{11}}x_n^{(k)} \\ 
	         x_2^{(k+1)} = \frac{b_2}{a_{22}}  - \frac{a_{21}}{a_{22}}x_1^{(k)} - \frac{a_{23}}{a_{22}}x_3^{(k)} - \cdots - \frac{a_{1n}}{a_{11}}x_n^{(k)} \\ 
	         \vdots   \\
	         x_n^{(k+1)} = \frac{b_n}{a_{nn}}  - \frac{a_{n1}}{a_{nn}}x_1^{(k)} - \frac{a_{n2}}{a_{nn}}x_3^{(k)} - \cdots - \frac{a_{n \, n-1}}{a_{nn}}x_{n-1}^{(k)} \\
\end{cases} $$





### Convergência
Se a matriz $A=(a_{ij})_{i,j=1.,,,,n}$ do sistema $Ax=b$ for estritamente diagonalmente dominante, ou seja,

$$ |a_{ii}| > \sum_{j=1,i\neq j} |a_{ij}| , i=1,...n$$

então, o método iterativo de Jacobi-Richardson será convergente. 

### Critério de parada 
Considerando que o processo iterativo está fornecendo uma sequência convergente, um critério de parada para o algoritmo pode ser dado por

$$ \frac{\parallel x^n - x^{n-1}\parallel }{\parallel x^n\parallel} < \epsilon$$

para alguma norma vetorial $\parallel . \parallel : V \rightarrow R$ e alguma tolerância $\epsilon$ pré estabelecida. 

Por conveniência, é comum utilizarmos a norma infinito:

$$\parallel x\parallel _ \infty = max \{ |x_0|, |x_1|, ..., |x_n| \}$$.

#### Exemplo 1
Usando o método interativo de Jacobi-Richardson, determine uma solução aproximada para o seguinte sistema de equações lineares, com aproximação inicial $x^{0}=(0,0,0)^t$ e precisão $\epsilon = 0.01$. 

$$
\left[\begin{array}{ccc} 
10 & 2 & 1\\
1 & 5 & 1\\
2 & 3 & 10\\
\end{array} \right]
\left[\begin{array}{c} 
x_1\\
x_2\\
x_3\\
\end{array} \right]
=
\left[\begin{array}{c} 
14\\
11\\
8\\
\end{array} \right]
$$

*Solução:*

Reescrevendo o sistema, obtemos:

$$ 
\begin{cases} 
x_1^{(k+1)} = \frac{14}{10} - \frac{2}{10}x_2^{(k)} - \frac{1}{10}x_3^{(k)}\\ 
x_2^{(k+1)} = \frac{11}{5} - \frac{1}{5}x_1^{(k)} - \frac{1}{5}x_3^{(k)}\\ 
x_3^{(k+1)} = \frac{8}{10} - \frac{2}{10}x_1^{(k)} - \frac{3}{10}x_2^{(k)}\\ 
\end{cases} 
$$

Em pyton podemos fazer como segue

In [40]:
x = np.array([0.,0.,0.])

In [41]:
def itera(x):
    x1 = 1.4 - 0.2*x[1] - 0.1*x[2]
    x2 = 2.2 - 0.2*x[0] - 0.2*x[2]
    x3 = 0.8 - 0.2*x[0] - 0.3*x[1]
    x = np.array([x1, x2, x3])
    return x

In [42]:
#uma iteração
x = itera(x)
print ("k=1,", "x=",x)

k=1, x= [1.4 2.2 0.8]


In [43]:
#várias iterações e o erro
x_ant = x
for i in range(2,7):
    x = itera(x)
    err = np.max(abs(x-x_ant))/np.max(abs(x))
    x_ant = x
    print (i, x, err)

2 [ 0.88  1.76 -0.14] 0.5340909090909091
3 [1.062 2.052 0.096] 0.1423001949317738
4 [ 0.98    1.9684 -0.028 ] 0.06299532615322088
5 [1.00912 2.0096  0.01348] 0.02064092356687896
6 [ 0.996732  1.99548  -0.004704] 0.009112594463487526


Na forma matricial, o podemos escrever o processo iterativo da seguinte maneira, 

$$ x^{(k+1)} = Hx^{(k)} + g $$

onde 

<p style="text-align:center;">
$H = 
\left[\begin{array}{ccccc} 
 0 & -\frac{a_{12}}{a_{11}} & -\frac{a_{13}}{a_{11}} &\cdots & -\frac{a_{1n}}{a_{11}} \\ 
 -\frac{a_{21}}{a_{22}} & 0 & -\frac{a_{23}}{a_{22}} &\cdots & -\frac{a_{2n}}{a_{22}} \\
  \vdots & \vdots & \vdots & \vdots & \vdots \\
 -\frac{a_{n1}}{a_{nn}} & -\frac{a_{n2}}{a_{nn}} & -\frac{a_{n3}}{a_{nn}}&\cdots & 0 \\
\end{array} \right]
\,\,\,\,\,\,$
e
$\,\,\,\,\,\,g = 
\left[\begin{array}{c} 
\frac{b_1}{a_{11}} \\ 
\frac{b_2}{a_{22}} \\
\vdots \\
\frac{b_n}{a_{nn}}\\
\end{array} \right]
$
</p>

ou, ainda,


$$
\left[\begin{array}{c} 
x_1^{k+1} \\ 
x_2^{k+1} \\
\vdots \\
x_n^{k+1}\\
\end{array} \right]
= 
\left[\begin{array}{ccccc} 
 0 & -\frac{a_{12}}{a_{11}} & -\frac{a_{13}}{a_{11}} &\cdots & -\frac{a_{1n}}{a_{11}} \\ 
 -\frac{a_{21}}{a_{22}} & 0 & -\frac{a_{23}}{a_{22}} &\cdots & -\frac{a_{2n}}{a_{22}} \\
  \vdots & \vdots & \vdots & \vdots & \vdots \\
 -\frac{a_{n1}}{a_{nn}} & -\frac{a_{n2}}{a_{nn}} & -\frac{a_{n3}}{a_{nn}}&\cdots & 0 \\
\end{array} \right]
\left[\begin{array}{c} 
x_1^{k} \\ 
x_2^{k} \\
\vdots \\
x_n^{k}\\
\end{array} \right]
+
\left[\begin{array}{c} 
\frac{b_1}{a_{11}} \\ 
\frac{b_2}{a_{22}} \\
\vdots \\
\frac{b_n}{a_{nn}}\\
\end{array} \right]
$$

### Convergência

Seja uma norma matricial consistente com alguma norma vetorial, se $\parallel H \parallel < 1$ então a sequência será convergente. Em geral, para verificar a convergência usamos a norma infinito 

$$\parallel H \parallel _\infty = max_{1 \leq i \leq n}  \left\{ \sum_{j=1}^n |a_{ij}|  \right\} $$

## Exemplos  Jacobi-Richardson

In [44]:
import numpy as np

(x1,x2) = (0,0)

f = lambda x1,x2: (1-0.5*x2, 1+0.5*x1)

for i in range(10):
    (x1,x2) = f(x1, x2)
    print (x1,x2)


1.0 1.0
0.5 1.5
0.25 1.25
0.375 1.125
0.4375 1.1875
0.40625 1.21875
0.390625 1.203125
0.3984375 1.1953125
0.40234375 1.19921875
0.400390625 1.201171875


In [45]:
x = [0,0,0]

x1 = lambda x2, x3: 1.4 - 0.2*x2 - 0.1*x3
x2 = lambda x1, x3: 2.2 - 0.2*x1 - 0.2*x3
x3 = lambda x1, x2: 0.8 - 0.2*x1 - 0.3*x2

for k in range(20):
     x = [x1(x[1],x[2]), x2(x[0],x[2]), x3(x[0],x[1])]
     print ("(%.4f,"%x[0],"%.4f,"%x[1],"%.4f)"%x[2])

(1.4000, 2.2000, 0.8000)
(0.8800, 1.7600, -0.1400)
(1.0620, 2.0520, 0.0960)
(0.9800, 1.9684, -0.0280)
(1.0091, 2.0096, 0.0135)
(0.9967, 1.9955, -0.0047)
(1.0014, 2.0016, 0.0020)
(0.9995, 1.9993, -0.0008)
(1.0002, 2.0003, 0.0003)
(0.9999, 1.9999, -0.0001)
(1.0000, 2.0000, 0.0000)
(1.0000, 2.0000, -0.0000)
(1.0000, 2.0000, 0.0000)
(1.0000, 2.0000, -0.0000)
(1.0000, 2.0000, 0.0000)
(1.0000, 2.0000, -0.0000)
(1.0000, 2.0000, 0.0000)
(1.0000, 2.0000, -0.0000)
(1.0000, 2.0000, 0.0000)
(1.0000, 2.0000, -0.0000)


Um outro programa, agora usando operações vetoriais com o Numpy

In [46]:
import numpy as np
from numpy import linalg as LA

A = np.array([[10.0, 2.0, 1.0],
              [ 1.0, 5.0, 1.0],
              [ 2.0, 3.0, 10.0]])
b = np.array([14., 11., 8.])

x = np.array([0,0,0])
x_ant = x.copy()

n = len(A)
H = A.copy()
g = b.copy()
err = 10.0


for i in range(n):
    H[i] = -A[i]/A[i][i]
    g[i] = b[i]/A[i,i]
    
H = H + np.identity(3) #zerando os elementos da diagonal
print (H)
print ("Norma inf. de H=", LA.norm(H, np.inf))

while err>0.001:
    x = np.dot(H,x)+g
    err = abs(max(x-x_ant)/max(x))
    x_ant = x
print(x)

    


[[ 0.  -0.2 -0.1]
 [-0.2  0.  -0.2]
 [-0.2 -0.3  0. ]]
Norma inf. de H= 0.5
[ 9.9948016e-01  1.9993232e+00 -7.5320000e-04]


## Método iterativo de Gaus-Seidel

Considere um sistema  de equações lineares $Ax = b$ em que $det(A) \neq 0$, com a diagonal principal $a_{ii} \neq 0$, $i=1,...,n$ como segue

$$ \begin{cases} 
	         a_{11}x_1 +a_{12}x_2 + \cdots + a_{1n}x_n = b_1\\ 
	         a_{21}x_1 +a_{22}x_2 + \cdots + a_{2n}x_n = b_2\\
	         \vdots   \\
	         a_{n1}x_1 +a_{n2}x_2 + \cdots + a_{nn}x_n = b_1\\
             \end{cases} $$

Dividindo cada linha do sistema dado pelo elemento da diagonal e isolando $x_1$ na $1^a$ equação, $x_2$ na $2^a$ equação até $x_n$ na n-ésima equação, temos o sistema escrito na forma equivalente:

$$ \begin{cases} 
	         x_1 = \frac{1}{a_{11}} \left(b_1  - a_{12}x_2 - a_{13}x_3 - \cdots - a_{1n}x_n \right)\\ 
	         x_2 = \frac{1}{a_{22}} \left(b_2  - a_{21}x_1 - a_{23}x_3 - \cdots - a_{2n}x_n \right)\\ 
	         \vdots   \\
	         x_n = \frac{1}{a_{nn}} \left(b_n  - a_{n1}x_1 - a_{n2}x_2 - \cdots - a_{n \, n-1}x_{n-1} \right)\\ 
\end{cases} $$

O método iterativo de Gauss-Seidel é dado da seguinte forma:

$$ \begin{cases} 
             x_1^{(k+1)} = \frac{b_1}{a_{11}}  - \frac{a_{12}}{a_{11}}x_2^{(k)} - \frac{a_{13}}{a_{11}}x_3^{(k)} - \cdots - \frac{a_{1n}}{a_{11}}x_n^{(k)} \\ 
	         x_2^{(k+1)} = \frac{b_2}{a_{22}}  - \frac{a_{21}}{a_{22}}x_1^{(k+1)} - \frac{a_{23}}{a_{22}}x_3^{(k)} - \cdots - \frac{a_{1n}}{a_{11}}x_n^{(k)} \\ 
	         \vdots   \\
	         x_n^{(k+1)} = \frac{b_n}{a_{nn}}  - \frac{a_{n1}}{a_{nn}}x_1^{(k+1)} - \frac{a_{n2}}{a_{nn}}x_3^{(k+1)} - \cdots - \frac{a_{n \, n-1}}{a_{nn}}x_{n-1}^{(k+1)} \\
\end{cases} $$


## Exemplos

In [47]:
import numpy as np

x = np.array([0.,0.,0.])
x_ant = np.array([0.,0.,0.])
eps = 0.01

A = np.array([[-10., 2.0, 2.0],
              [ 1.0, 6.0, 0.0],
              [-1.0, 1.0, 3.0]])
b = np.array([-8., 7., 0.])

x1 = lambda x2, x3: (b[0] - A[0,1]*x2 - A[0,2]*x3)/A[0,0]
x2 = lambda x1, x3: (b[1] - A[1,0]*x1 - A[1,2]*x3)/A[1,1]
x3 = lambda x1, x2: (b[2] - A[2,0]*x1 - A[2,1]*x2)/A[2,2]

err = 10.
while err>eps:
#for k in range(5):
    x[0] = x1(x[1],x[2])
    x[1] = x2(x[0],x[2])
    x[2] = x3(x[0],x[1])
    err = np.amax(np.absolute(x-x_ant))/np.amax(np.absolute(x))   
    print ("(%.4f,"%x[0],"%.4f,"%x[1],"%.4f)"%x[2], "err=",err)
    x_ant = np.copy(x)

(0.8000, 1.0333, -0.0778) err= 1.0
(0.9911, 1.0015, -0.0035) err= 0.19082840236686394
(0.9996, 1.0001, -0.0002) err= 0.00849326793297563


In [48]:
import numpy as np

x = np.array([0.,0.,0.])
x_ant = np.array([0.,0.,0.])
eps = 0.01

A = np.array([[10,2,1],
              [1,5,1],
              [2,3,10]])
b = np.array([14,11,8])

x1 = lambda x2, x3: (b[0] - A[0,1]*x2 - A[0,2]*x3)/A[0,0]
x2 = lambda x1, x3: (b[1] - A[1,0]*x1 - A[1,2]*x3)/A[1,1]
x3 = lambda x1, x2: (b[2] - A[2,0]*x1 - A[2,1]*x2)/A[2,2]

err = 10.
while err>eps:
#for k in range(5):
    x[0] = x1(x[1],x[2])
    x[1] = x2(x[0],x[2])
    x[2] = x3(x[0],x[1])
    err = np.amax(np.absolute(x-x_ant))/np.amax(np.absolute(x))   
    print ("(%.4f,"%x[0],"%.4f,"%x[1],"%.4f)"%x[2], "err=",err)
    x_ant = np.copy(x)

(1.4000, 1.9200, -0.0560) err= 1.0
(1.0216, 2.0069, -0.0064) err= 0.18855138324164877
(0.9993, 2.0014, -0.0003) err= 0.011160851687861838
(0.9997, 2.0001, 0.0000) err= 0.0006584584230122856


In [49]:
import numpy as np

x = np.array([0.,0.,0.,0,0])
x_ant = np.array([0.,0.,0.,0,0])
eps = 0.001

A = np.array([[5,1,2,1,-1],
              [0,6,1,1,-1],
              [0,1,-3,2,1],
              [3,0,2,7,0],
              [1,1,0,0,8]])
b = np.array([1,2,0,2,1])

x1 = lambda x2, x3, x4, x5: (b[0] - A[0,1]*x2 - A[0,2]*x3 - A[0,3]*x4 - A[0,4]*x5)/A[0,0]
x2 = lambda x1, x3, x4, x5: (b[1] - A[1,0]*x1 - A[1,2]*x3 - A[1,3]*x4 - A[1,4]*x5)/A[1,1]
x3 = lambda x1, x2, x4, x5: (b[2] - A[2,0]*x1 - A[2,1]*x2 - A[2,3]*x4 - A[2,4]*x5)/A[2,2]
x4 = lambda x1, x2, x3, x5: (b[3] - A[3,0]*x1 - A[3,1]*x2 - A[3,2]*x3 - A[3,4]*x5)/A[3,3]
x5 = lambda x1, x2, x3, x4: (b[4] - A[4,0]*x1 - A[4,1]*x2 - A[4,2]*x3 - A[4,3]*x4)/A[4,4]

err = 10.
while err>eps:
#for k in range(5):
    x[0] = x1(x[1],x[2],x[3],x[4])
    x[1] = x2(x[0],x[2],x[3],x[4])
    x[2] = x3(x[0],x[1],x[3],x[4])
    x[3] = x4(x[0],x[1],x[2],x[4])
    x[4] = x5(x[0],x[1],x[2],x[3])
    err = np.amax(np.absolute(x-x_ant))/np.amax(np.absolute(x))   
    print ("(%.4f,"%x[0],"%.4f,"%x[1],"%.4f,"%x[2],"%.4f,"%x[3],"%.4f,)"%x[4], "err=",err)
    x_ant = np.copy(x)

(0.2000, 0.3333, 0.1111, 0.1683, 0.0583,) err= 1.0
(0.0669, 0.2965, 0.2304, 0.1912, 0.0796,) err= 0.44889582868614764
(0.0262, 0.2763, 0.2461, 0.2042, 0.0872,) err= 0.14731623998678267
(0.0229, 0.2728, 0.2561, 0.2027, 0.0880,) err= 0.03672029746344947
(0.0201, 0.2715, 0.2550, 0.2043, 0.0886,) err= 0.010484703792705703
(0.0205, 0.2715, 0.2562, 0.2037, 0.0885,) err= 0.004427429100359636
(0.0202, 0.2714, 0.2558, 0.2040, 0.0886,) err= 0.0015913196833542652
(0.0203, 0.2715, 0.2560, 0.2039, 0.0885,) err= 0.0008282016028652112


Na forma matricial, o método de Gauss-Seidel  pode ser escrito como

$$\left[
    \begin{array}{c} 
	         x_1^{(k+1)} \\ 
	         x_2^{(k+1)} \\
             \vdots\\
	         x_n^{(k+1)} \\
	\end{array} 
\right]
=
\left[\begin{array}{ccccc} 
	         0                     & 0 & 0 & \cdots & 0 \\ 
	         -\frac{a_{21}}{a_{22}} & 0 & 0 & \cdots & 0 \\
	         \vdots & \vdots & \vdots & \vdots & \vdots \\
	         -\frac{a_{n1}}{a_{nn}} & -\frac{a_{n2}}{a_{nn}} & \cdots & -\frac{a_{n \,n-1}}{a_{nn}} & 0\\
	         \end{array} \right]
             \left[
    \begin{array}{c} 
	         x_1^{(k+1)} \\ 
	         x_2^{(k+1)} \\
             \vdots\\
	         x_n^{(k+1)} \\
	\end{array} 
\right]
+
\left[\begin{array}{ccccc} 
	         0&  -\frac{a_{12}}{a_{11}}& -\frac{a_{13}}{a_{11}}& \cdots &-\frac{a_{1n}}{a_{11}} \\ 
	         0& 0& -\frac{a_{23}}{a_{22}} & \cdots & -\frac{a_{2n}}{a_{22}} \\
	         \vdots & \vdots & \vdots & \vdots & \vdots \\
	         0& 0& 0& \cdots& 0\\
	         \end{array} \right]
\left[\begin{array}{c} 
	         x_1^{(k)} \\ 
	         x_2^{(k)} \\
             \vdots\\
	         x_n^{(k)} \\
	\end{array} \right]
+
\left[ \begin{array}{c} 
	         \frac{b_1}{a_{11}} \\ 
	         \frac{b_2}{a_{22}} \\
             \vdots\\
	         \frac{b_n}{a_{nn}} \\
	\end{array} \right]$$


ou 
$$ x^{(k+1)} = P x^{(k+1)} + Q x^{(k)} + g$$

$$ (I-P)x^{(k+1)} = Q x^{(k)} + g$$

$$ x^{(k+1)} = (I-P)^{-1}Q x^{(k)} + (I-P)^{-1}g$$

Fazendo-se $H = (I-P)^{-1}Q$ e $g' =(I-P)^{-1}g$ o processo iterativo torna-se

$$x^{(k+1)} = H x^{(k)} + g'$$

Agora usando operações vetoriais com Numpy

In [50]:
import numpy as np

x = np.array([0.,0.,0.,0,0])
x_ant = x.copy()
eps = 0.001

A = np.array([[5,1,2,1,-1],
              [0,6,1,1,-1],
              [0,1,-3,2,1],
              [3,0,2,7,0],
              [1,1,0,0,8]])
b = np.array([1,2,0,2,1])

n = len(A)
for k in range(10):
    for i in range(n):
        x[i] = (b[i] - np.dot(A[i,0:i],x[0:i])-np.dot(A[i,i+1:n],x[i+1:n]))/A[i,i]

print (np.round(x,4))
    
    
    
    
    

[0.0203 0.2715 0.2559 0.2039 0.0885]


In [51]:
from numpy.linalg import inv


x = np.array([0.,0.,0.,0,0])

eps = 0.001
A = np.array([[5,1,2,1,-1],
              [0,6,1,1,-1],
              [0,1,-3,2,1],
              [3,0,2,7,0],
              [1,1,0,0,8]])
b = np.array([1,2,0,2,1])

n = len(A)
P = np.zeros((n,n))
Q = np.zeros((n,n))
g = np.zeros(n)


for i in range(n):
    P[i,0:i] = -A[i,0:i]/A[i,i]
    Q[i,i+1:n] = -A[i,i+1:n]/A[i,i]
    g[i] = b[i]/A[i,i] 
    
I = np.eye(n)
H = np.dot(inv(I-P),Q)
g = np.dot(inv(I-P),g)


for k in range(10):
    x = np.dot(H,x) + g
    
    print (np.round(x,4))



[0.2    0.3333 0.1111 0.1683 0.0583]
[0.0669 0.2965 0.2304 0.1912 0.0796]
[0.0262 0.2763 0.2461 0.2042 0.0872]
[0.0229 0.2728 0.2561 0.2027 0.088 ]
[0.0201 0.2715 0.255  0.2043 0.0886]
[0.0205 0.2715 0.2562 0.2037 0.0885]
[0.0202 0.2714 0.2558 0.204  0.0886]
[0.0203 0.2715 0.256  0.2039 0.0885]
[0.0202 0.2714 0.2559 0.2039 0.0885]
[0.0203 0.2715 0.2559 0.2039 0.0885]


### Referências

FRANCO, Neide Maria Bertoldi . Cálculo Numérico.  Pearson, 2006.

KIUSALAAS, Jaan. Numerical Methods in Engineering with Python 3. Cambridge: University Press, 2013.

RUGGIERO, M.A.G. & LOPES, V.L. Cálculo numérico: aspectos teóricos e computacionais. São Paulo: Makron Books, 1996.
