# 0.2 O básico sobre Numpy

## Vectors, Matrices, and Multidimensional Arrays

Vetores, matrizes e _arrays_ de dimensões superiores são ferramentas essenciais na computação numérica. Quando um o cálculo deve ser repetido para um conjunto de valores de entrada, é natural e vantajoso representar o
dados como _arrays_ e o cálculo em termos de operações entre _arrays_.

Processamento computacional numérico formulado dessa forma são ditos vetorizados. A computação vetorizada elimina a necessidade de muitos _loops_ explícitos sobre os elementos da matriz, aplicando operações em blocos de dados da matriz. 

O resultado é um código conciso e mais fácil de entender e gerenciar, além disso, permite realizar operações em bibliotecas de baixo nível, mais eficientes. Computações vetorizadas podem, portanto, ser significativamente mais rápidas do que cálculos sequenciais elemento a elemento. 

Isso é particularmente importante em uma linguagem interpretada como Python, onde laços elemento a elemento resultam em uma demanda de desempenho significativa.

No ambiente de computação científica do Python, estruturas de dados eficientes para trabalhar com matrizes são fornecido pela biblioteca NumPy. 

O núcleo do NumPy é implementado em C e fornece funções eficientes
para manipular e processar matrizes. 

À primeira vista, os arrays NumPy têm alguma semelhança com o Python
listar estrutura de dados. Mas uma diferença importante é que, enquanto as listas do Python são recipientes genéricos de objetos,
Os arrays NumPy são homogêneos e datilografam matrizes de tamanho fixo. Homogênea significa que todos os elementos no
array tem o mesmo tipo de dados. Tamanho fixo significa que um array não pode ser redimensionado (sem criar um novo
array). Por essas e outras razões, as operações e funções que atuam nos arrays NumPy podem ser muito mais
eficiente do que operações em listas do Python. Além das estruturas de dados para matrizes, o NumPy também fornece
uma grande coleção de operadores e funções básicas que atuam nessas estruturas de dados, bem como submódulos
com algoritmos de nível superior, como álgebra linear e transformações rápidas de Fourier.
Neste capítulo, primeiro examinamos a estrutura de dados NumPy básica para matrizes e vários métodos para
criar tais matrizes NumPy. Em seguida, examinamos as operações para manipular arrays e para fazer cálculos
com matrizes. O array de dados multidimensional fornecido pelo NumPy é uma base para quase todos os
bibliotecas para Python. Gastar tempo para se familiarizar com o NumPy e desenvolver um entendimento de como
O trabalho do NumPy é, portanto, importante.


## Vetorizando uma função

Ocasionalmente é necessário definir novas funções que operam em matrizes numpy em uma base elemento-por-elemento. Uma boa maneira de implementar essas funções é expressá-la em termos de operadores numpy já existentes e expressões, mas em casos em que isso não é possível, a função np. vectorize pode ser uma ferramenta conveniente. Essa função usa uma função não-vetorial e retorna uma função vetorial. Por exemplo, considere a seguinte implementação da função Step Heaviside, que funciona para entrada escalar:


In [3]:
def heaviside(x):
    return 1 if x>0 else 0

print(heaviside(-1))

0


In [4]:
print(heaviside(1.5))

1


In [6]:
import numpy as np
x = np.linspace(-5,5,11)
print (x)

[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]


In [7]:
heaviside(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [8]:
heaviside = np.vectorize(heaviside)
heaviside(x) 

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

## Manipulando matrizes


### Exemplo
construindo a matriz ampliada (A|b) para processar a eliminação de Gauss

In [27]:
A = np.array([[4,-2,1],[-2,4,-2],[1,-2,4]])
print (A)

[[ 4 -2  1]
 [-2  4 -2]
 [ 1 -2  4]]


In [28]:
b = np.array([11,-16,17])
print (b)

[ 11 -16  17]


In [29]:
b = b.reshape(3,1)
print (b)

[[ 11]
 [-16]
 [ 17]]


In [30]:
Ab = np.hstack((A, b))
print (Ab)

[[  4  -2   1  11]
 [ -2   4  -2 -16]
 [  1  -2   4  17]]
