# 0.2 Comandos básicos em  Numpy

Numpy é o pacote fundamental para programação científica que proporciona um objeto tipo **array** para armazenar dados de forma eficiente e dispõe de uma série de funções para operar e manipular esses dados. Para usar Numpy, uma vez que já esteja instalado, é importá-lo. Para isso podemos usar a seguinte linha de comando, que importa e chama de **np**.

In [42]:
import numpy as np

## Deferença entre listas e arrays 

Os arrays do Numpy são muito parecidos com as listas do Python, mas possuem diferenças importantes que devem ser conhecidas. Uma diferença importante é que as listas do Python podem armazenar diferentes tipos de dados (int, floar, str, etc) enquanto os arrays do NumPy são homogêneos (mesmo tipo de dado) e representam vetores e matrizes de tamanho fixo, ou seja, não podem ser redimensionados (sem criar um novo array).

Por exemplo, observe que a forma de acessar elementos de _lista_ e de _array_ é a mesma 

In [49]:
x = [1, 2, 3, -1]     # x é uma lista do python  
y = [-2, 3, 0.3, 1]   # y também é uma lista do python
print (x[2])          # imprime o 3º elemento de x
print (y[-1])         # imprime o último elemento de y

3
1


In [52]:
import numpy as np
u = np.array([2, 5, 0.5, 10])    # u é um array do numpy
v = np.array([-1, 0.5, 1.2, 3])  # v também é um array do numpy
print (u[0])                     # imprime o 1º elemento de u
print (v[-2])                    # imprime o penúltimo elemento de v

2.0
1.2


Apesar das semalhanças entre listas e arrays, as operações com arrays do Numpy são feitas elemento a elemento. Então, devemos ter cuidado para não confundir as operações com realizadas com arrays e com listas, pois um mesmo operador pode gerar resultados muito diferentes. Veja os exemplos abaixo.

In [53]:
# x e y são listas python
print(2*x) 

[1, 2, 3, -1, 1, 2, 3, -1]


In [54]:
print(x+y)

[1, 2, 3, -1, -2, 3, 0.3, 1]


In [55]:
print(x**2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [46]:
print(2*v)
print(v+u)
print(v**2)

[-2.   1.   2.4  6. ]
[ 1.   5.5  1.7 13. ]
[1.   0.25 1.44 9.  ]


## Vetores, matrices e arrays multidimensionais

Vetores, matrizes e _arrays_ de dimensões superiores são ferramentas essenciais na computação numérica. Quando um o cálculo deve ser repetido para um conjunto de valores de entrada, é natural e vantajoso representar o dados como _arrays_ e processar cálculos em termos de operações entre _arrays_.

Processamento computacional numérico formulado dessa forma são ditos vetorizados. A computação vetorizada elimina a necessidade de muitos _loops_ explícitos sobre os elementos da matriz, aplicando operações em blocos de dados da matriz. 

O resultado é um código conciso e mais fácil de entender e gerenciar, além disso, permite realizar operações em bibliotecas de baixo nível (BLAS, LAPACK,etc), mais eficientes. Computações vetorizadas podem, portanto, ser significativamente mais rápidas do que cálculos sequenciais elemento a elemento. 

Isso é particularmente importante em uma linguagem interpretada como Python, onde laços elemento a elemento resultam em uma demanda de desempenho significativa. 

No ambiente de computação científica do Python, estruturas de dados eficientes para trabalhar com matrizes são fornecido pela biblioteca NumPy. O núcleo do NumPy é implementado em C e fornece funções eficientes para manipular e processar matrizes. 

À primeira vista, os arrays NumPy têm alguma semelhança com as listas do Python. Mas uma diferença importante é que, enquanto as listas do Python são recipientes genéricos de objetos, os arrays NumPy são homogêneos e datilografam matrizes de tamanho fixo. Homogênea significa que todos os elementos no
array tem o mesmo tipo de dados. Tamanho fixo significa que um array não pode ser redimensionado (sem criar um novo array).

Por essas e outras razões, as operações e funções que atuam nos arrays NumPy podem ser muito mais eficiente do que operações em listas do Python. Além das estruturas de dados para matrizes, o NumPy também fornece uma grande coleção de operadores e funções básicas que atuam nessas estruturas de dados, bem como submódulos com algoritmos de nível superior, como álgebra linear e transformações rápidas de Fourier.


### Criando e manipulando arrays e matrizes
Uma forma simples de criar um array é a partir de uma lista, mas também existem finções para criar array de zeros, ou vazios, conforme é mostrado nos exemplos a seguir.

In [58]:
a = np.array([2, 3, 5, -1])
print (a)

[ 2  3  5 -1]


In [59]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [68]:
np.zeros(3)

array([0., 0., 0.])

In [85]:
np.eye(4,4,1)  # matriz com uma diagonal deslocada formada de 1s

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [69]:
np.empty(3)

array([0., 0., 0.])

In [80]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [86]:
np.linspace(2,5,7)  # pontos igualmente espaçados (ini, fim, n de pontos)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

Outras operações muito úteis ao lidar com arrays em computação científica e numérica são o recorte de arrays, inversão de linhas ou colunas, concatenação de matrizes, e outras que são exemplificadas a seguir. 

In [ ]:
w = np.array([1, 2, -1, 3, -4, 2, 5])


#### Exemplo
construindo a matriz ampliada (A|b) para processar a eliminação de Gauss

In [47]:
A = np.array([[4,-2,1],[-2,4,-2],[1,-2,4]])
print (A)

b = np.array([11,-16,17])
print (b)

b = b.reshape(3,1)
print (b)

Ab = np.hstack((A, b))
print (Ab)

[[ 4 -2  1]
 [-2  4 -2]
 [ 1 -2  4]]
[ 11 -16  17]
[[ 11]
 [-16]
 [ 17]]
[[  4  -2   1  11]
 [ -2   4  -2 -16]
 [  1  -2   4  17]]


### Vetorizando uma função

Ocasionalmente é necessário definir novas funções que operam em matrizes numpy em uma base elemento-por-elemento. Uma boa maneira de implementar essas funções é expressá-la em termos de operadores numpy já existentes e expressões, mas em casos em que isso não é possível, a função np. vectorize pode ser uma ferramenta conveniente. Essa função usa uma função não-vetorial e retorna uma função vetorial. Por exemplo, considere a seguinte implementação da função Step Heaviside, que funciona para entrada escalar:


In [3]:
def heaviside(x):
    return 1 if x>0 else 0

print(heaviside(-1))

0


In [4]:
print(heaviside(1.5))

1


In [6]:
import numpy as np
x = np.linspace(-5,5,11)
print (x)

[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]


In [7]:
heaviside(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [8]:
heaviside = np.vectorize(heaviside)
heaviside(x) 

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

### Operações básicas com arrays
As operações com arrays do Numpy são feitas elemento a elemento. 

#### Exemplo

In [33]:
import numpy as np
v = np.array([1, 2, 3, -1])
u = np.array([2, 5, 0.5, 10])
print (2*v)

[ 2  4  6 -2]


In [34]:
print (u+v)

[3.  7.  3.5 9. ]


In [35]:
print (3+v)

[4 5 6 2]


In [36]:
print (u*v)

[  2.   10.    1.5 -10. ]


In [13]:
print (u**2)

[  4.    25.     0.25 100.  ]


Calculando o produto interno (ou produto de matrizes)

In [37]:
print (np.dot(u,v))

3.5


In [40]:
A = np.array([[2,1],[-1,4]])
B = np.array([[5,-1],[8,3]])
print(np.dot(A,B))

[[18  1]
 [27 13]]


Somando os elementos de um array

In [38]:
print(np.sum(v))

5


In [41]:
print(np.max(v))

3
